language: java
dist: trusty
jdk:
  - openjdk8
  
notifications:
  email:
    - alexander.fedorov@arsysop.ru
    - sergei.kovalchuk@arsysop.ru
    
cache:
  directories:
  - $HOME/.m2

before_install: echo "MAVEN_OPTS='-Xmx2048m'" > ~/.mavenrc

install: true

script: mvn clean verify -U -Pcoverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
